"use client";

import { siteConfig } from "@/config/site";
import { LegalArticle } from "@/components/legal/legal-article";
import { LocaleLink } from "@/components/locale-link";

export function PrivacyPolicyBody() {
  const domain = siteConfig.domain.replace(/^https?:\/\//, "").replace(/\/$/, "");

  return (
    <LegalArticle>
      <h1>Privacy notice &amp; GDPR information</h1>
      <p>
        This notice explains how <strong>{siteConfig.fullName}</strong> (“we”, “us”) processes personal
        data when you visit <strong>{domain}</strong> or use the contact form. We aim to comply with the
        EU General Data Protection Regulation (GDPR) and applicable national law in Finland. This document
        is for transparency; it does not constitute legal advice. Last updated: 15 April 2026.
      </p>

      <h2>1. Data controller</h2>
      <p>
        <strong>{siteConfig.fullName}</strong>
        <br />
        Email: <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>
        <br />
        General privacy &amp; GDPR requests: <a href="mailto:gdpr@awunjia.com">gdpr@awunjia.com</a>
      </p>

      <h2>2. What data we process and why</h2>

      <h3>2.1 Browsing the portfolio</h3>
      <p>
        When you load pages, we and/or our hosting infrastructure <strong>may collect your IP address</strong>{" "}
        together with typical technical data (for example user agent, timestamp, requested URL) in server
        or edge logs. This is used to deliver the site, diagnose errors, and protect against abuse.
        Depending on configuration, this processing may be based on{" "}
        <strong>legitimate interests</strong> (Article 6(1)(f) GDPR) in operating and securing an online
        presence, or on a hosting contract.
      </p>

      <h3>2.2 Consent, language, and theme</h3>
      <p>
        If you use the cookie banner, we record your choices in a first-party cookie. If you enable
        preferences, we store language and theme selections as described in the{" "}
        <LocaleLink href="/legal/cookies">Cookie policy</LocaleLink>. Legal bases: <strong>consent</strong> (Article
        6(1)(a) GDPR) for non-essential storage, and where applicable <strong>legitimate interests</strong>{" "}
        for minimal operational cookies.
      </p>

      <h3>2.3 Contact form</h3>
      <p>
        When you contact us through the form, we collect the information you choose to send. That
        typically includes:
      </p>
      <ul>
        <li>
          <strong>Your name</strong> and <strong>email address</strong> (so we can identify and reach you).
        </li>
        <li>
          <strong>The content of your message</strong> (for example your enquiry or introduction text).
        </li>
        <li>
          <strong>Any file you upload</strong> (for example a CV, portfolio sample, or other project-related
          attachment), including the file name and contents as you submit them.
        </li>
        <li>
          <strong>Your IP address</strong> (and related technical metadata such as headers) as received
          by our server or mail path when the form is submitted — used for security, abuse prevention, and
          troubleshooting.
        </li>
        <li>
          If enabled, data generated by <strong>Cloudflare Turnstile</strong> to help verify that the
          submission is not automated abuse.
        </li>
      </ul>
      <p>
        <strong>Why we use this information:</strong> we use it only to read and respond to your message
        (for example to <strong>contact you back</strong> about your enquiry or anything you uploaded). We do not use the
        contact form to build marketing profiles and we <strong>do not sell your information to third parties</strong>.
      </p>
      <p>
        Legal basis: <strong>legitimate interests</strong> (Article 6(1)(f) GDPR) and/or{" "}
        <strong>pre-contractual steps</strong> at your request (Article 6(1)(b) GDPR), depending on the
        nature of your enquiry. Where we rely on legitimate interests, you may object as described
        below; we balance our interest in receiving genuine enquiries against your rights.
      </p>

      <h3>2.4 Open-source page</h3>
      <p>
        Repository metadata is fetched from GitHub&apos;s public API when you load that page. Your IP
        address may be processed by GitHub as an independent controller or processor under their
        policies.
      </p>

      <h2>3. Recipients and processors</h2>
      <p>
        Depending on how the site is deployed, data may be processed on our behalf by service providers
        strictly as needed to run the site and deliver messages (for example):
      </p>
      <ul>
        <li>
          <strong>Hosting / infrastructure</strong> (for example VPS, platform-as-a-service, or reverse
          proxy) that stores or transmits log files and site content.
        </li>
        <li>
          <strong>Cloudflare</strong> (Turnstile, DNS, TLS, CDN, and{" "}
          <strong>R2 object storage</strong> for optional contact-form attachments) under their terms and
          privacy documentation.
        </li>
        <li>
          <strong>Email delivery</strong> providers or self-hosted mail transport used to forward contact
          messages.
        </li>
      </ul>
      <p>
        <strong>We do not sell your personal data to third parties.</strong> We do not share your contact
        form contents for unrelated marketing or data brokerage. Processors act under instructions and
        contracts where the GDPR requires them.
      </p>

      <h2>4. International transfers</h2>
      <p>
        Some providers may process data outside the European Economic Area (EEA). Where required, we rely
        on appropriate safeguards such as Standard Contractual Clauses or the provider&apos;s adequacy
        decisions, as described in their documentation.
      </p>

      <h2>5. Retention</h2>
      <ul>
        <li>Consent and preference records: as set out in the Cookie policy (typically up to 180 days).</li>
        <li>
          Contact messages: kept only as long as needed to respond and for a reasonable follow-up
          period, unless a longer period is required by law.
        </li>
        <li>Server logs: according to hosting defaults, usually rotated after a limited period.</li>
      </ul>

      <h2>6. Your rights (GDPR)</h2>
      <p>If the GDPR applies to you, you may have the right to:</p>
      <ul>
        <li>Access your personal data (Article 15)</li>
        <li>Rectify inaccurate data (Article 16)</li>
        <li>Erase data (“right to be forgotten”) in certain cases (Article 17)</li>
        <li>Restrict processing (Article 18)</li>
        <li>Data portability, where applicable (Article 20)</li>
        <li>Object to processing based on legitimate interests (Article 21)</li>
        <li>Withdraw consent at any time, where processing is consent-based (Article 7(3))</li>
        <li>Lodge a complaint with a supervisory authority (Article 77)</li>
      </ul>
      <p>
        To exercise rights or request <strong>deletion of data</strong> arising from this site or the
        contact form, email <a href="mailto:gdpr@awunjia.com">gdpr@awunjia.com</a>. We will respond within
        one month where the GDPR requires it (that period may be extended by two further months where
        necessary, in line with Article 12(3)).
      </p>

      <h2>7. Security</h2>
      <p>
        We use reasonable technical and organisational measures appropriate to a small portfolio site
        (for example TLS, access control on servers, and spam protection on forms). No online transmission
        is completely secure.
      </p>

      <h2>8. Children</h2>
      <p>
        The site is not directed at children under 16. If you believe a child has provided personal data,
        contact us and we will take steps to delete it where required.
      </p>

      <h2>9. Automated decision-making</h2>
      <p>We do not use automated decision-making or profiling within the meaning of Article 22 GDPR.</p>

      <h2>10. Changes</h2>
      <p>
        We may update this notice when our processing changes. The “Last updated” date will change
        accordingly. Continued use after changes constitutes acknowledgement where legally appropriate.
      </p>

      <h2>11. Supervisory authority</h2>
      <p>
        In Finland, the supervisory authority is the Office of the Data Protection Ombudsman (Tietosuoja).
        You have the right to lodge a complaint with them or with the authority in your country of
        residence or work.
      </p>
    </LegalArticle>
  );
}
